"""Protocol-specific clients for Honua Server surfaces.

This package fans out the FeatureServer/MapServer/ImageServer/GeometryServer,
OGC API Maps/Tiles/Coverages/Processes, STAC, WFS, WMS, WMTS, and OData clients
across focused submodules. The same public names that used to live at
``honua_sdk.protocols`` (e.g. :class:`FeatureServerClient`,
:class:`BinaryResponse`, :class:`ODataQuery`) are re-exported here for
backward compatibility, so callers can keep importing them from
``honua_sdk.protocols`` unchanged.
"""

# Re-exports below intentionally surface private helpers (``_SyncProtocol``,
# ``_per_call_kwargs``, etc.) so callers that imported them from the legacy
# ``protocols.py`` monolith continue to work; F401 fires on names that are
# not in ``__all__`` even though importers rely on them.
# ruff: noqa: F401

from __future__ import annotations

from ._base import (
    BboxValue,
    BinaryResponse,
    CsvValue,
    FeatureId,
    JsonObject,
    JsonResponseFormat,
    ODataOrderBy,
    ODataQuery,
    OgcImageFormat,
    Params,
    WfsVersion,
    WmsVersion,
    WmtsVersion,
    _AsyncProtocol,
    _bbox,
    _bool_text,
    _csv,
    _features_from_page,
    _next_link,
    _normalize_max_pages,
    _normalize_page_limit,
    _normalize_total_limit,
    _odata_params,
    _ogc_collection_path,
    _params,
    _path_and_params_from_href,
    _per_call_kwargs,
    _query_value,
    _service_path,
    _SyncProtocol,
    _values_from_page,
)
from .geoservices import (
    AsyncGeoServicesFeatureServerClient,
    AsyncGeoServicesGeometryServerClient,
    AsyncGeoServicesImageServerClient,
    AsyncGeoServicesMapServerClient,
    GeoServicesFeatureServerClient,
    GeoServicesGeometryServerClient,
    GeoServicesImageServerClient,
    GeoServicesMapServerClient,
)
from .odata import AsyncODataClient, ODataClient
from .ogc_extras import (
    AsyncOgcCoveragesClient,
    AsyncOgcMapsClient,
    AsyncOgcProcessesClient,
    AsyncOgcRecordsClient,
    AsyncOgcRecordsCollectionClient,
    AsyncOgcTilesClient,
    OgcCoveragesClient,
    OgcMapsClient,
    OgcProcessesClient,
    OgcRecordsClient,
    OgcRecordsCollectionClient,
    OgcTilesClient,
)
from .scenes import (
    CURRENT_PACKAGE_SCHEMA_VERSION,
    AsyncElevationClient,
    AsyncSceneClient,
    ElevationClient,
    ElevationProfile,
    ElevationProfileSample,
    ElevationSourceMetadata,
    ElevationValue,
    HonuaSceneAccessCachePolicy,
    HonuaSceneAccessEnvelope,
    HonuaSceneAccessModes,
    HonuaSceneAuthRequirements,
    HonuaSceneBounds,
    HonuaSceneCapabilities,
    HonuaSceneCoordinate,
    HonuaSceneEndpoint,
    HonuaSceneError,
    HonuaSceneLink,
    HonuaSceneMetadata,
    HonuaScenePackageAsset,
    HonuaScenePackageAssetTypes,
    HonuaScenePackageBuildAsset,
    HonuaScenePackageBuildResult,
    HonuaScenePackageByteBudget,
    HonuaScenePackageEditionGates,
    HonuaScenePackageError,
    HonuaScenePackageLod,
    HonuaScenePackageManifest,
    HonuaScenePackageState,
    HonuaScenePackageValidationCodes,
    HonuaScenePackageValidationIssue,
    HonuaScenePackageValidationResult,
    HonuaScenePackageValidationSeverity,
    HonuaSceneResolution,
    HonuaSceneSummary,
    HonuaTilesetContent,
    SceneClient,
    enumerate_tileset_contents,
    parse_scene_package_manifest,
    validate_scene_package_manifest,
)
from .stac import AsyncStacClient, StacClient
from .wfs import AsyncWfsClient, WfsClient
from .wms import AsyncWmsClient, WmsClient
from .wmts import AsyncWmtsClient, WmtsClient

__all__ = [
    "CURRENT_PACKAGE_SCHEMA_VERSION",
    "AsyncElevationClient",
    "AsyncGeoServicesFeatureServerClient",
    "AsyncGeoServicesGeometryServerClient",
    "AsyncGeoServicesImageServerClient",
    "AsyncGeoServicesMapServerClient",
    "AsyncODataClient",
    "AsyncOgcCoveragesClient",
    "AsyncOgcMapsClient",
    "AsyncOgcProcessesClient",
    "AsyncOgcRecordsClient",
    "AsyncOgcRecordsCollectionClient",
    "AsyncOgcTilesClient",
    "AsyncSceneClient",
    "AsyncStacClient",
    "AsyncWfsClient",
    "AsyncWmsClient",
    "AsyncWmtsClient",
    "BboxValue",
    "BinaryResponse",
    "CsvValue",
    "ElevationClient",
    "ElevationProfile",
    "ElevationProfileSample",
    "ElevationSourceMetadata",
    "ElevationValue",
    "FeatureId",
    "GeoServicesFeatureServerClient",
    "GeoServicesGeometryServerClient",
    "GeoServicesImageServerClient",
    "GeoServicesMapServerClient",
    "HonuaSceneAccessCachePolicy",
    "HonuaSceneAccessEnvelope",
    "HonuaSceneAccessModes",
    "HonuaSceneAuthRequirements",
    "HonuaSceneBounds",
    "HonuaSceneCapabilities",
    "HonuaSceneCoordinate",
    "HonuaSceneEndpoint",
    "HonuaSceneError",
    "HonuaSceneLink",
    "HonuaSceneMetadata",
    "HonuaScenePackageAsset",
    "HonuaScenePackageAssetTypes",
    "HonuaScenePackageBuildAsset",
    "HonuaScenePackageBuildResult",
    "HonuaScenePackageByteBudget",
    "HonuaScenePackageEditionGates",
    "HonuaScenePackageError",
    "HonuaScenePackageLod",
    "HonuaScenePackageManifest",
    "HonuaScenePackageState",
    "HonuaScenePackageValidationCodes",
    "HonuaScenePackageValidationIssue",
    "HonuaScenePackageValidationResult",
    "HonuaScenePackageValidationSeverity",
    "HonuaSceneResolution",
    "HonuaSceneSummary",
    "HonuaTilesetContent",
    "JsonObject",
    "JsonResponseFormat",
    "ODataClient",
    "ODataOrderBy",
    "ODataQuery",
    "OgcCoveragesClient",
    "OgcImageFormat",
    "OgcMapsClient",
    "OgcProcessesClient",
    "OgcRecordsClient",
    "OgcRecordsCollectionClient",
    "OgcTilesClient",
    "Params",
    "SceneClient",
    "StacClient",
    "WfsClient",
    "WfsVersion",
    "WmsClient",
    "WmsVersion",
    "WmtsClient",
    "WmtsVersion",
    "enumerate_tileset_contents",
    "parse_scene_package_manifest",
    "validate_scene_package_manifest",
]
