"""Honua Python SDK -- data-plane and protocol clients.

Optional GeoPandas integration is available via ``honua_sdk.geopandas``::

    from honua_sdk.geopandas import features_to_geodataframe, geodataframe_to_features

Install with:  ``pip install honua-sdk[geopandas]``
"""

from __future__ import annotations

try:
    from importlib.metadata import version as _meta_version

    __version__: str = _meta_version("honua-sdk")
except Exception:  # pragma: no cover -- editable / not-installed fallback
    __version__ = "0.0.0.dev0"

from .auth import (
    AuthProvider,
    BearerToken,
    CallableAuthProvider,
    InMemoryTokenStore,
    RefreshableBearerTokenProvider,
    StaticAuthProvider,
    TokenStore,
)
from .async_client import AsyncHonuaClient
from .async_geocoding import AsyncHonuaGeocodingClient
from .client import HonuaClient
from .errors import HonuaCapabilityNotSupportedError, HonuaError, HonuaGrpcError, HonuaHttpError
from .etl import (
    AsyncHonuaEtl,
    ConnectorConfig,
    HonuaEtl,
    PipelineDefinition,
    PipelineExecution,
    PipelineExecutionError,
    PipelineStage,
    SinkStage,
    SourceStage,
    TransformConfig,
    TransformStage,
)
from .geoprocessing import (
    AsyncHonuaGeoprocessing,
    GeoprocessingJob,
    GeoprocessingJobError,
    HonuaGeoprocessing,
    LayerReference,
)
# Eagerly import the migration subpackage so ``from honua_sdk import migration``
# and ``honua_sdk.migration`` resolve without a separate import. It is a
# subpackage, not added to ``__all__`` (module objects are not part of the
# public-API snapshot surface, which renders exports via ``repr``).
from . import migration
from .geocoding import (
    GeocodeResult,
    GeocodeSuggestion,
    HonuaGeocodingClient,
    ReverseGeocodeResult,
)
from .models import (
    ApplyEditsResult,
    CAPABILITIES,
    DEFAULT_CAPABILITIES,
    PROTOCOLS,
    PROTOCOL_ALIASES,
    Capability,
    DataPlaneCapabilities,
    DegradedReason,
    EditOperationResult,
    Feature,
    FeatureQuery,
    FeatureQueryResult,
    FeatureSet,
    Pagination,
    Protocol,
    Query,
    QueryFeature,
    QueryProtocol,
    Result,
    ServiceSummary,
    SourceDescriptor,
    SourceLocator,
    capability_set,
    default_capabilities,
    normalize_capability,
    normalize_protocol,
)
from .ogc import (
    AsyncHonuaOgcFeatureCollection,
    AsyncHonuaOgcFeatures,
    HonuaOgcFeatureCollection,
    HonuaOgcFeatures,
)
from .protocols import (
    AsyncGeoServicesFeatureServerClient,
    AsyncGeoServicesGeometryServerClient,
    AsyncGeoServicesImageServerClient,
    AsyncGeoServicesMapServerClient,
    AsyncODataClient,
    AsyncOgcCoveragesClient,
    AsyncOgcMapsClient,
    AsyncOgcProcessesClient,
    AsyncOgcRecordsClient,
    AsyncOgcRecordsCollectionClient,
    AsyncOgcTilesClient,
    AsyncStacClient,
    AsyncWfsClient,
    AsyncWmsClient,
    AsyncWmtsClient,
    BboxValue,
    BinaryResponse,
    CsvValue,
    FeatureId,
    GeoServicesFeatureServerClient,
    GeoServicesGeometryServerClient,
    GeoServicesImageServerClient,
    GeoServicesMapServerClient,
    JsonObject,
    JsonResponseFormat,
    ODataClient,
    ODataOrderBy,
    ODataQuery,
    OgcCoveragesClient,
    OgcImageFormat,
    OgcMapsClient,
    OgcProcessesClient,
    OgcRecordsClient,
    OgcRecordsCollectionClient,
    OgcTilesClient,
    StacClient,
    WfsClient,
    WfsVersion,
    WmsClient,
    WmsVersion,
    WmtsClient,
    WmtsVersion,
)
from .source import AsyncSource, Source

__all__ = [
    "__version__",
    "AuthProvider",
    "AsyncHonuaClient",
    "AsyncHonuaEtl",
    "AsyncHonuaGeocodingClient",
    "AsyncHonuaGeoprocessing",
    "AsyncGeoServicesFeatureServerClient",
    "AsyncGeoServicesGeometryServerClient",
    "AsyncGeoServicesImageServerClient",
    "AsyncGeoServicesMapServerClient",
    "AsyncHonuaOgcFeatureCollection",
    "AsyncHonuaOgcFeatures",
    "AsyncODataClient",
    "AsyncOgcCoveragesClient",
    "AsyncOgcMapsClient",
    "AsyncOgcProcessesClient",
    "AsyncOgcRecordsClient",
    "AsyncOgcRecordsCollectionClient",
    "AsyncOgcTilesClient",
    "AsyncSource",
    "AsyncStacClient",
    "AsyncWfsClient",
    "AsyncWmsClient",
    "AsyncWmtsClient",
    "ApplyEditsResult",
    "BboxValue",
    "BearerToken",
    "BinaryResponse",
    "CAPABILITIES",
    "DEFAULT_CAPABILITIES",
    "Capability",
    "CallableAuthProvider",
    "ConnectorConfig",
    "CsvValue",
    "DataPlaneCapabilities",
    "DegradedReason",
    "EditOperationResult",
    "Feature",
    "FeatureQuery",
    "FeatureQueryResult",
    "FeatureId",
    "FeatureSet",
    "GeocodeResult",
    "GeocodeSuggestion",
    "GeoprocessingJob",
    "GeoprocessingJobError",
    "GeoServicesFeatureServerClient",
    "GeoServicesGeometryServerClient",
    "GeoServicesImageServerClient",
    "GeoServicesMapServerClient",
    "HonuaClient",
    "HonuaCapabilityNotSupportedError",
    "HonuaError",
    "HonuaEtl",
    "HonuaGrpcError",
    "HonuaHttpError",
    "HonuaGeocodingClient",
    "HonuaGeoprocessing",
    "HonuaOgcFeatureCollection",
    "HonuaOgcFeatures",
    "InMemoryTokenStore",
    "LayerReference",
    "JsonObject",
    "JsonResponseFormat",
    "ODataClient",
    "ODataOrderBy",
    "ODataQuery",
    "OgcCoveragesClient",
    "OgcImageFormat",
    "OgcMapsClient",
    "OgcProcessesClient",
    "OgcRecordsClient",
    "OgcRecordsCollectionClient",
    "OgcTilesClient",
    "PROTOCOLS",
    "PROTOCOL_ALIASES",
    "Pagination",
    "PipelineDefinition",
    "PipelineExecution",
    "PipelineExecutionError",
    "PipelineStage",
    "Protocol",
    "Query",
    "QueryFeature",
    "QueryProtocol",
    "RefreshableBearerTokenProvider",
    "ReverseGeocodeResult",
    "Result",
    "ServiceSummary",
    "SinkStage",
    "Source",
    "SourceDescriptor",
    "SourceLocator",
    "SourceStage",
    "StacClient",
    "StaticAuthProvider",
    "TokenStore",
    "TransformConfig",
    "TransformStage",
    "WfsClient",
    "WfsVersion",
    "WmsClient",
    "WmsVersion",
    "WmtsClient",
    "WmtsVersion",
    "capability_set",
    "default_capabilities",
    "normalize_capability",
    "normalize_protocol",
]
